TRUTH  = (
    "Apakah kamu pernah membuat hantu seseorang?"  "Pernahkah kamu mendatangi orang tuamu melakukan 'itu'?" ,
    "Siapa orang yang selalu buat kamu nyaman? tag orangnya!!" ,
    "Apakah kamu pernah diskors dari sekolah?" ,
    "Apa yang akan kamu lakukan ketika sendirian di dalam rumah?" ,
    "Apa satu hal yang kamu takut kehilangan?" ,
    "Apakah kamu menyukai seseorang untuk saat ini?" ,
    "Apa makanan kesukaanmu?" ,
    "Ibu atau Ayah?" ,
    "Apa pencapaian terbesar kamu?" ,
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?" ,
    "Sebutkan tipe ideal yang kamu inginkan untuk jadi pacar mu." ,
    "Apa hal paling menakutkan yang pernah kamu lakukan?" ,
    "Apakah kamu pernah mengupil dan memakannya?" ,
    "Negara mana yang pengen kamu kunjungi?" ,
    "Apakah Anda pernah berbohong tentang usia Anda untuk berpartisipasi dalam kontes?" ,
    "Sebutkan film favorit kamu?" ,
)

DARE  = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tampilkan lima orang terakhir yang Anda kirimi SMS dan apa isi pesannya" ,
    "Biarkan seluruh grup DM seseorang dari akun Instagram Anda" ,
    "Makan bawang putih mentah" ,
    "Lakukan 100 squat" ,
    "Simpan tiga es batu di mulutmu sampai meleleh" ,
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!" ,
    "Berikan pijatan kaki pada orang di sebelah kanan Anda" ,
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah" ,
    "*Katakan kata pertama yang muncul di pikiranmu" ,
    "Berikan lap dance kepada seseorang pilihan Anda" ,
    "Lepaskan empat potong pakaian" ,
    "Suka 15 posting pertama di umpan berita Facebook Anda" ,
    "Makan sesendok mustard" ,
    "Pejamkan matamu sampai kamu pergi lagi" ,
    "Kirim sext ke orang terakhir di buku telepon Anda" ,
    "Pamerkan wajah orgasme Anda" ,
    "Makan pisang dengan menggoda" ,
    "Kosongkan dompet/dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya" ,
    "Lakukan perayapan seksi terbaikmu" ,
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit" ,
    "Makan snack tanpa menggunakan tangan" ,
    "Katakan dua hal jujur ​​tentang semua orang dalam grup" ,
    "Twerk sebentar" ,
    "Cobalah membuat grup tertawa secepat mungkin" ,
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu" ,
    "Ceritakan kepada semua orang kisah memalukan tentang diri Anda" ,
    "Coba jilat sikumu" ,
    "Posting selfie tertua di ponsel Anda di Instagram Stories" ,
    "Ceritakan kisah paling menyedihkan yang kamu tahu" ,
    "Melolong seperti serigala selama dua menit" ,
    "Menari tanpa musik selama dua menit" ,
    "Tari tiang dengan tiang imajiner" ,
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa" ,
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa" ,
    "Kirim selfie terbaru Anda." ,
    "Kirim selfiemu yang paling jelek." ,
    "Kirim tangkapan layar riwayat pencarian facebook Anda" ,
    "Kirim tangkapan layar galeri Anda." ,
    "Kirim tangkapan layar kotak masuk messenger Anda" ,
    "Ceritakan sesuatu yang sangat intim." ,
    "Kirim tangkapan layar kotak masuk twitter Anda" ,
    "Kirim tangkapan layar layar beranda Anda." ,
    "Kirim cover lagu favoritmu. " ,
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya." ,
    "Akui gebetanmu saat ini. ❤️" ,
    "Ungkapkan siapa cinta sejatimu." ,
    "Kirim tangkapan layar galeri Anda." ,
    "Jadikan foto gebetanmu sebagai dpmu." ,
    "Sarankan aku lebih berani." ,
)
